"""新 detector 的字段标签定义。"""

from __future__ import annotations

from privacyguard.domain.enums import PIIAttributeType
from privacyguard.infrastructure.pii.detector.models import LabelSpec, NameComponentHint

_LABEL_SPECS: tuple[LabelSpec, ...] = (
    LabelSpec("邮箱地址", PIIAttributeType.EMAIL, 320, "context_email_field", "ocr_label_email_field"),
    LabelSpec("电子邮箱", PIIAttributeType.EMAIL, 319, "context_email_field", "ocr_label_email_field"),
    LabelSpec("邮箱", PIIAttributeType.EMAIL, 318, "context_email_field", "ocr_label_email_field"),
    LabelSpec("email address", PIIAttributeType.EMAIL, 317, "context_email_field", "ocr_label_email_field", ascii_boundary=True),
    LabelSpec("e-mail", PIIAttributeType.EMAIL, 316, "context_email_field", "ocr_label_email_field", ascii_boundary=True),
    LabelSpec("email", PIIAttributeType.EMAIL, 315, "context_email_field", "ocr_label_email_field", ascii_boundary=True),
    LabelSpec("手机号码", PIIAttributeType.PHONE, 314, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("手机号", PIIAttributeType.PHONE, 313, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("手机", PIIAttributeType.PHONE, 312, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("移动电话", PIIAttributeType.PHONE, 311, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("联系电话", PIIAttributeType.PHONE, 310, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("电话", PIIAttributeType.PHONE, 309, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("座机", PIIAttributeType.PHONE, 308, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("固定电话", PIIAttributeType.PHONE, 307, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("服务热线", PIIAttributeType.PHONE, 306, "context_phone_field", "ocr_label_phone_field"),
    LabelSpec("phone number", PIIAttributeType.PHONE, 305, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("mobile phone", PIIAttributeType.PHONE, 304, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("mobile", PIIAttributeType.PHONE, 303, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("cellphone", PIIAttributeType.PHONE, 302, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("cell", PIIAttributeType.PHONE, 301, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("telephone", PIIAttributeType.PHONE, 300, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("tel", PIIAttributeType.PHONE, 299, "context_phone_field", "ocr_label_phone_field", ascii_boundary=True),
    LabelSpec("证件号码", PIIAttributeType.ID_NUMBER, 298, "context_id_field", "ocr_label_id_field"),
    LabelSpec("公民身份号码", PIIAttributeType.ID_NUMBER, 297, "context_id_field", "ocr_label_id_field"),
    LabelSpec("身份证", PIIAttributeType.ID_NUMBER, 296, "context_id_field", "ocr_label_id_field"),
    LabelSpec("身份证号", PIIAttributeType.ID_NUMBER, 295, "context_id_field", "ocr_label_id_field"),
    LabelSpec("身份证号码", PIIAttributeType.ID_NUMBER, 294, "context_id_field", "ocr_label_id_field"),
    LabelSpec("id number", PIIAttributeType.ID_NUMBER, 293, "context_id_field", "ocr_label_id_field", ascii_boundary=True),
    LabelSpec("national id", PIIAttributeType.ID_NUMBER, 292, "context_id_field", "ocr_label_id_field", ascii_boundary=True),
    LabelSpec("护照号码", PIIAttributeType.PASSPORT_NUMBER, 291, "context_passport_field", "ocr_label_passport_field"),
    LabelSpec("护照号", PIIAttributeType.PASSPORT_NUMBER, 290, "context_passport_field", "ocr_label_passport_field"),
    LabelSpec("护照", PIIAttributeType.PASSPORT_NUMBER, 289, "context_passport_field", "ocr_label_passport_field"),
    LabelSpec("passport number", PIIAttributeType.PASSPORT_NUMBER, 288, "context_passport_field", "ocr_label_passport_field", ascii_boundary=True),
    LabelSpec("passport", PIIAttributeType.PASSPORT_NUMBER, 287, "context_passport_field", "ocr_label_passport_field", ascii_boundary=True),
    LabelSpec("驾驶证", PIIAttributeType.DRIVER_LICENSE, 286, "context_driver_license_field", "ocr_label_driver_license_field"),
    LabelSpec("驾照", PIIAttributeType.DRIVER_LICENSE, 285, "context_driver_license_field", "ocr_label_driver_license_field"),
    LabelSpec("驾驶证号", PIIAttributeType.DRIVER_LICENSE, 284, "context_driver_license_field", "ocr_label_driver_license_field"),
    LabelSpec("driver license", PIIAttributeType.DRIVER_LICENSE, 283, "context_driver_license_field", "ocr_label_driver_license_field", ascii_boundary=True),
    LabelSpec("drivers license", PIIAttributeType.DRIVER_LICENSE, 282, "context_driver_license_field", "ocr_label_driver_license_field", ascii_boundary=True),
    LabelSpec("dl number", PIIAttributeType.DRIVER_LICENSE, 281, "context_driver_license_field", "ocr_label_driver_license_field", ascii_boundary=True),
    LabelSpec("银行卡号", PIIAttributeType.CARD_NUMBER, 280, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("信用卡号", PIIAttributeType.CARD_NUMBER, 279, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("信用卡", PIIAttributeType.CARD_NUMBER, 278, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("储蓄卡卡号", PIIAttributeType.CARD_NUMBER, 277, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("储蓄卡", PIIAttributeType.CARD_NUMBER, 276, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("借记卡卡号", PIIAttributeType.CARD_NUMBER, 275, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("借记卡", PIIAttributeType.CARD_NUMBER, 274, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("银联卡号", PIIAttributeType.CARD_NUMBER, 273, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("卡号", PIIAttributeType.CARD_NUMBER, 272, "context_card_number_field", "ocr_label_card_number_field"),
    LabelSpec("card number", PIIAttributeType.CARD_NUMBER, 271, "context_card_number_field", "ocr_label_card_number_field", ascii_boundary=True),
    LabelSpec("credit card", PIIAttributeType.CARD_NUMBER, 270, "context_card_number_field", "ocr_label_card_number_field", ascii_boundary=True),
    LabelSpec("debit card", PIIAttributeType.CARD_NUMBER, 269, "context_card_number_field", "ocr_label_card_number_field", ascii_boundary=True),
    LabelSpec("pan", PIIAttributeType.CARD_NUMBER, 268, "context_card_number_field", "ocr_label_card_number_field", ascii_boundary=True),
    LabelSpec("银行账号", PIIAttributeType.BANK_ACCOUNT, 267, "context_bank_account_field", "ocr_label_bank_account_field"),
    LabelSpec("银行帐户", PIIAttributeType.BANK_ACCOUNT, 266, "context_bank_account_field", "ocr_label_bank_account_field"),
    LabelSpec("收款账号", PIIAttributeType.BANK_ACCOUNT, 265, "context_bank_account_field", "ocr_label_bank_account_field"),
    LabelSpec("对公账号", PIIAttributeType.BANK_ACCOUNT, 264, "context_bank_account_field", "ocr_label_bank_account_field"),
    LabelSpec("开户账号", PIIAttributeType.BANK_ACCOUNT, 263, "context_bank_account_field", "ocr_label_bank_account_field"),
    LabelSpec("bank account", PIIAttributeType.BANK_ACCOUNT, 262, "context_bank_account_field", "ocr_label_bank_account_field", ascii_boundary=True),
    LabelSpec("iban", PIIAttributeType.BANK_ACCOUNT, 261, "context_bank_account_field", "ocr_label_bank_account_field", ascii_boundary=True),
    LabelSpec("routing number", PIIAttributeType.BANK_ACCOUNT, 260, "context_bank_account_field", "ocr_label_bank_account_field", ascii_boundary=True),
    LabelSpec("公司名称", PIIAttributeType.ORGANIZATION, 259, "context_organization_field", "ocr_label_organization_field"),
    LabelSpec("单位名称", PIIAttributeType.ORGANIZATION, 258, "context_organization_field", "ocr_label_organization_field"),
    LabelSpec("organization", PIIAttributeType.ORGANIZATION, 257, "context_organization_field", "ocr_label_organization_field", ascii_boundary=True),
    LabelSpec("company name", PIIAttributeType.ORGANIZATION, 256, "context_organization_field", "ocr_label_organization_field", ascii_boundary=True),
    LabelSpec("company", PIIAttributeType.ORGANIZATION, 255, "context_organization_field", "ocr_label_organization_field", ascii_boundary=True),
    LabelSpec("家庭住址", PIIAttributeType.ADDRESS, 254, "context_address_field", "ocr_label_address_field"),
    LabelSpec("联系地址", PIIAttributeType.ADDRESS, 253, "context_address_field", "ocr_label_address_field"),
    LabelSpec("住址", PIIAttributeType.ADDRESS, 252, "context_address_field", "ocr_label_address_field"),
    LabelSpec("地址", PIIAttributeType.ADDRESS, 251, "context_address_field", "ocr_label_address_field"),
    LabelSpec("address line", PIIAttributeType.ADDRESS, 250, "context_address_field", "ocr_label_address_field", ascii_boundary=True),
    LabelSpec("address", PIIAttributeType.ADDRESS, 249, "context_address_field", "ocr_label_address_field", ascii_boundary=True),
    LabelSpec("住客姓名", PIIAttributeType.NAME, 248, "context_name_field", "ocr_label_name_field", NameComponentHint.FULL),
    LabelSpec("姓名", PIIAttributeType.NAME, 247, "context_name_field", "ocr_label_name_field", NameComponentHint.FULL),
    LabelSpec("full name", PIIAttributeType.NAME, 246, "context_name_field", "ocr_label_name_field", NameComponentHint.FULL, True),
    LabelSpec("name", PIIAttributeType.NAME, 245, "context_name_field", "ocr_label_name_field", NameComponentHint.FULL, True),
    LabelSpec("surname", PIIAttributeType.NAME, 244, "context_name_family_field", "ocr_label_name_family_field", NameComponentHint.FAMILY, True),
    LabelSpec("family name", PIIAttributeType.NAME, 243, "context_name_family_field", "ocr_label_name_family_field", NameComponentHint.FAMILY, True),
    LabelSpec("last name", PIIAttributeType.NAME, 242, "context_name_family_field", "ocr_label_name_family_field", NameComponentHint.FAMILY, True),
    LabelSpec("姓", PIIAttributeType.NAME, 241, "context_name_family_field", "ocr_label_name_family_field", NameComponentHint.FAMILY),
    LabelSpec("given name", PIIAttributeType.NAME, 240, "context_name_given_field", "ocr_label_name_given_field", NameComponentHint.GIVEN, True),
    LabelSpec("first name", PIIAttributeType.NAME, 239, "context_name_given_field", "ocr_label_name_given_field", NameComponentHint.GIVEN, True),
    LabelSpec("名", PIIAttributeType.NAME, 238, "context_name_given_field", "ocr_label_name_given_field", NameComponentHint.GIVEN),
    LabelSpec("middle name", PIIAttributeType.NAME, 237, "context_name_middle_field", "ocr_label_name_middle_field", NameComponentHint.MIDDLE, True),
)

__all__ = ["_LABEL_SPECS"]
